# This is a basic workflow to help you get started with Actions

name: this-repo-build-push-to-dockerhub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: 
    -  '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Build and push the image to Container Registry
      - name: Build and Push container to registry
        run: |
          docker build --file=Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/dotnetcore-webapi:${{ env.GITHUB_TAG }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dotnetcore-webapi:${{ env.GITHUB_TAG }}
